sudo: required
language: java
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - pip3 install requests
script:
- mvn verify -B
- mvn checkstyle:check -pl trading-api
- mvn checkstyle:check -pl application
- mvn clean install
- mvn exec:java -pl application & > logs.txt
- python3 infra-test/main.py 