matrix:
  include:
    - language: java
      script:
        - mvn verify -B
        - mvn checkstyle:check -pl trading-api
        - mvn checkstyle:check -pl application
    - language: python
      python: 
        - 3.4
      install: 
        - pip install requests
      before_install:
        - cd infra-test/
      script:
        - python main.py